version:  '3.7'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  sah-api:
    image: uanorman/sah-api
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    entrypoint: php bin/console server:run 0.0.0.0:8000
    environment:
      - MONGO_URL=mongodb://mongodb:27017
  sah-app:
    image: uanorman/ads-sah-app
    ports:
      - "3000:3000"
    entrypoint: npm run start:production
    depends_on:
      - sah-api
  fetch-ads-service:
    image: uanorman/fetch-ads-service
    depends_on:
      - sah-api
    environment:
      - API_URL=http://sah-api:8000/ads
    command: ["sh", "-c", "php ./fetch.php" ]
volumes:
  data: